/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTE8 (number 11), LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE9 (number 12), LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD8 (number 137), DSPdp
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPdp_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPdp_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPdp_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPdp_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPdp_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD9 (number 138), DSPa
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPa_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPa_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPa_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPa_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPa_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD10 (number 139), DSPb
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPb_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPb_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPb_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPb_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPb_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD11 (number 140), DSPc
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPc_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPc_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPc_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPc_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPc_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD12 (number 141), DSPd
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPd_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPd_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPd_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPd_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPd_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD13 (number 142), DSPe
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPe_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPe_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPe_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPe_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPe_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD14 (number 143), DSPf
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPf_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPf_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPf_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPf_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPf_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD15 (number 144), DSPg
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPg_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPg_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPg_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPg_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPg_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE12 (number 15), BEEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BEEP_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BEEP_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BEEP_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BEEP_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BEEP_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (number 96), KEY1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY1_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY1_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY1_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB18 (number 97), KEY2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC7 (number 112), SW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC16 (number 123), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC17 (number 124), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW3_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW3_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC18 (number 125), SW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW4_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW4_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW4_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW4_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW4_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB20 (number 99), QESa
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESa_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESa_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESa_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESa_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESa_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB19 (number 98), QESb
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESb_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESb_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESb_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESb_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESb_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB21 (number 100), QESp
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESp_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESp_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESp_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESp_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESp_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE11 (number 14), I2C3_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SCL_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SCL_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE10 (number 13), I2C3_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SDA_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SDA_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA26 (number 77), OLED_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_SCL_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_SCL_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_SCL_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_SCL_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_SCL_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA27 (number 78), OLED_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_SDA_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_SDA_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_SDA_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_SDA_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_SDA_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA28 (number 79), OLED_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_RST_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_RST_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_RST_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_RST_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_RST_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA29 (number 80), OLED_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_DC_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_DC_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_DC_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_DC_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_DC_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB0 (number 81), CAMD0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD0_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD0_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB1 (number 82), CAMD1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB2 (number 83), CAMD2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD2_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB3 (number 84), CAMD3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD3_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB4 (number 85), CAMD4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD4_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD4_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD4_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD4_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB5 (number 86), CAMD5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD5_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD5_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD5_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD5_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD5_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB6 (number 87), CAMD6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD6_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD6_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD6_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD6_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD6_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB7 (number 88), CAMD7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMD7_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMD7_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMD7_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMD7_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMD7_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB8 (number 89), CAMPCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMPCLK_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMPCLK_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMPCLK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMPCLK_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMPCLK_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB9 (number 90), CAMSCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMSCL_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMSCL_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMSCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMSCL_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMSCL_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTB10 (number 91), CAMSDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMSDA_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMSDA_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMSDA_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMSDA_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMSDA_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB11 (number 92), CAMHREF
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMHREF_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMHREF_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMHREF_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMHREF_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMHREF_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB16 (number 95), CAMVSYN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAMVSYN_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CAMVSYN_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CAMVSYN_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CAMVSYN_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CAMVSYN_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA14 (number 66), DbgUart_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DbgUart_TX_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DbgUart_TX_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DbgUart_TX_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA15 (number 67), DbgUart_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DbgUart_RX_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DbgUart_RX_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DbgUart_RX_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name ADC0_DM0 (number 28), MEMSx
  @{ */
/* @} */

/*! @name ADC0_DP3 (number 29), MEMSy
  @{ */
/* @} */

/*! @name ADC1_DM0 (number 30), MEMSz
  @{ */
/* @} */

/*! @name PORTC5 (number 110), CCDCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CCDCLK_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CCDCLK_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CCDCLK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CCDCLK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CCDCLK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC6 (number 111), CCDSI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CCDSI_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CCDSI_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CCDSI_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CCDSI_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CCDSI_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC0 (number 103), CCDAO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CCDAO_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CCDAO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CCDAO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD0 (number 127), SERVO1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SERVO1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SERVO1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SERVO1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD1 (number 128), SERVO2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SERVO2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SERVO2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SERVO2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA9 (number 61), MLEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MLEN_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MLEN_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MLEN_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MLEN_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MLEN_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC15 (number 120), MREN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MREN_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MREN_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MREN_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MREN_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MREN_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTA5 (number 55), ML0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ML0_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ML0_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ML0_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA6 (number 58), ML1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ML1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ML1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ML1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD4 (number 131), MR0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MR0_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MR0_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MR0_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD7 (number 136), MR1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MR1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MR1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MR1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD6 (number 133), VSENSE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_VSENSE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_VSENSE_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_VSENSE_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name ADC1_SE18 (number 37), IRV1
  @{ */
/* @} */

/*! @name ADC0_SE23 (number 38), IRV2
  @{ */
/* @} */

/*! @name ADC1_SE23 (number 39), HALL1
  @{ */
/* @} */

/*! @name PORTE24 (number 45), HALL2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HALL2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HALL2_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HALL2_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
