/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MK66FN2M0xxx18
package_id: MK66FN2M0VLQ18
mcu_data: ksdk2_0
processor_version: 8.0.1
pin_labels:
- {pin_num: '15', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, label: BEEP, identifier: BEEP}
- {pin_num: '11', pin_signal: PTE8/I2S0_RXD1/I2S0_RX_FS/LPUART0_TX/FTM3_CH3, label: LED1, identifier: LED1}
- {pin_num: '12', pin_signal: PTE9/LLWU_P17/I2S0_TXD1/I2S0_RX_BCLK/LPUART0_RX/FTM3_CH4, label: LED2, identifier: LED2}
- {pin_num: '137', pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16, label: DSPdp, identifier: DSPdp}
- {pin_num: '138', pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17, label: DSPa, identifier: DSPa}
- {pin_num: '139', pin_signal: PTD10/LPUART0_RTS_b/FB_A18, label: DSPb, identifier: DSPb}
- {pin_num: '140', pin_signal: PTD11/LLWU_P25/SPI2_PCS0/SDHC0_CLKIN/LPUART0_CTS_b/FB_A19, label: DSPc, identifier: DSPc}
- {pin_num: '141', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FB_A20, label: DSPd, identifier: DSPd}
- {pin_num: '142', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, label: DSPe, identifier: DSPe}
- {pin_num: '143', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, label: DSPf, identifier: DSPf}
- {pin_num: '144', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, label: DSPg, identifier: DSPg}
- {pin_num: '96', pin_signal: TSI0_CH10/PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/SDRAM_D16/EWM_OUT_b/TPM_CLKIN1, label: KEY1, identifier: KEY1}
- {pin_num: '97', pin_signal: TSI0_CH11/PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/SDRAM_A23/FTM2_QD_PHA/TPM2_CH0, label: KEY2, identifier: KEY2}
- {pin_num: '112', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB0_SOF_OUT/I2S0_RX_FS/FB_AD8/SDRAM_A16, label: SW1, identifier: SW1}
- {pin_num: '123', pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b/SDRAM_DQM2, label: SW2, identifier: SW2}
- {pin_num: '124', pin_signal: PTC17/CAN1_TX/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b/SDRAM_DQM3, label: SW3, identifier: SW3}
- {pin_num: '125', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b/SDRAM_DQM1, label: SW4, identifier: SW4}
- {pin_num: '99', pin_signal: PTB20/SPI2_PCS0/FB_AD31/SDRAM_D31/CMP0_OUT, label: QESa, identifier: QESa}
- {pin_num: '98', pin_signal: TSI0_CH12/PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB/TPM2_CH1, label: QESb, identifier: QESb}
- {pin_num: '100', pin_signal: PTB21/SPI2_SCK/FB_AD30/SDRAM_D30/CMP1_OUT, label: QESp, identifier: QESp}
- {pin_num: '14', pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6, label: I2C3_SCL, identifier: I2C3_SCL}
- {pin_num: '13', pin_signal: PTE10/LLWU_P18/I2C3_SDA/I2S0_TXD0/LPUART0_CTS_b/FTM3_CH5/USB1_ID, label: I2C3_SDA, identifier: I2C3_SDA}
- {pin_num: '77', pin_signal: PTA26/MII0_TXD3/FB_A27, label: OLED_SCL, identifier: OLED_SCL}
- {pin_num: '78', pin_signal: PTA27/MII0_CRS/FB_A26, label: OLED_SDA, identifier: OLED_SDA}
- {pin_num: '79', pin_signal: PTA28/MII0_TXER/FB_A25, label: OLED_RST, identifier: OLED_RST}
- {pin_num: '80', pin_signal: PTA29/MII0_COL/FB_A24, label: OLED_DC, identifier: OLED_DC}
- {pin_num: '81', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0, label: CAMD0, identifier: CAMD0}
- {pin_num: '82', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1, label: CAMD1, identifier: CAMD1}
- {pin_num: '83', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/SDRAM_WE/FTM0_FLT3, label: CAMD2, identifier: CAM2;CAMD2}
- {pin_num: '84', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/SDRAM_CS0_b/FTM0_FLT0, label: CAMD3, identifier: CAMD3}
- {pin_num: '85', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/SDRAM_CS1_b/FTM1_FLT0, label: CAMD4, identifier: CAMD4}
- {pin_num: '86', pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, label: CAMD5, identifier: CAMD5}
- {pin_num: '87', pin_signal: ADC1_SE12/PTB6/FB_AD23/SDRAM_D23, label: CAMD6, identifier: CAMD6}
- {pin_num: '88', pin_signal: ADC1_SE13/PTB7/FB_AD22/SDRAM_D22, label: CAMD7, identifier: CAMD7}
- {pin_num: '89', pin_signal: PTB8/UART3_RTS_b/FB_AD21/SDRAM_D21, label: CAMPCLK, identifier: CAMPCLK}
- {pin_num: '90', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20/SDRAM_D20, label: CAMSCL, identifier: CAMSCL}
- {pin_num: '91', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/SDRAM_D19/FTM0_FLT1, label: CAMSDA, identifier: CAMSDA}
- {pin_num: '92', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/SDRAM_D18/FTM0_FLT2, label: CAMHREF, identifier: CAMDHREF;CAMHREF}
- {pin_num: '95', pin_signal: TSI0_CH9/PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/SDRAM_D17/EWM_IN/TPM_CLKIN0, label: CAMVSYN, identifier: CAMVSYN}
- {pin_num: '66', pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, label: DbgUart_TX, identifier: DBG_TX;DbgUart_TX}
- {pin_num: '67', pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, label: DbgUart_RX, identifier: DBG_RX;DbgUart_RX}
- {pin_num: '28', pin_signal: ADC0_DM0/ADC1_DM3, label: MEMSx, identifier: MEMSx}
- {pin_num: '29', pin_signal: ADC1_DP0/ADC0_DP3, label: MEMSy, identifier: MEMSy}
- {pin_num: '30', pin_signal: ADC1_DM0/ADC0_DM3, label: MEMSz, identifier: MEMSz}
- {pin_num: '110', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, label: CCDCLK, identifier: CCDCLK}
- {pin_num: '111', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK, label: CCDSI, identifier: CCDSI}
- {pin_num: '103', pin_signal: ADC0_SE14/TSI0_CH13/PTC0/SPI0_PCS4/PDB0_EXTRG/USB0_SOF_OUT/FB_AD14/SDRAM_A22/I2S0_TXD1, label: CCDAO, identifier: CCDAO}
- {pin_num: '127', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: SERVO1, identifier: SERVO1}
- {pin_num: '128', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: SERVO2, identifier: SERVO2}
- {pin_num: '61', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TPM1_CH1/TRACE_D1, label: MLEN, identifier: MLEN}
- {pin_num: '120', pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24, label: MREN, identifier: MREN}
- {pin_num: '55', pin_signal: PTA5/USB0_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, label: ML0, identifier: ML0}
- {pin_num: '58', pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, label: ML1, identifier: ML1}
- {pin_num: '131', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, label: MR0, identifier: MR0}
- {pin_num: '136', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, label: MR1, identifier: MR1}
- {pin_num: '133', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, label: VSENSE, identifier: VSENSE}
- {pin_num: '37', pin_signal: VREF_OUT/CMP1_IN5/CMP0_IN5/ADC1_SE18, label: IRV1, identifier: IRV1}
- {pin_num: '38', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23, label: IRV2, identifier: IRV2}
- {pin_num: '39', pin_signal: DAC1_OUT/CMP0_IN4/CMP2_IN3/ADC1_SE23, label: HALL1, identifier: HALL1}
- {pin_num: '45', pin_signal: ADC0_SE17/PTE24/CAN1_TX/UART4_TX/I2C0_SCL/EWM_OUT_b, label: HALL2, identifier: HALL2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: GPIOE, signal: 'GPIO, 8', pin_signal: PTE8/I2S0_RXD1/I2S0_RX_FS/LPUART0_TX/FTM3_CH3, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '12', peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: PTE9/LLWU_P17/I2S0_TXD1/I2S0_RX_BCLK/LPUART0_RX/FTM3_CH4, direction: OUTPUT, gpio_init_state: 'true',
    pull_select: up}
  - {pin_num: '137', peripheral: GPIOD, signal: 'GPIO, 8', pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '138', peripheral: GPIOD, signal: 'GPIO, 9', pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '139', peripheral: GPIOD, signal: 'GPIO, 10', pin_signal: PTD10/LPUART0_RTS_b/FB_A18, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '140', peripheral: GPIOD, signal: 'GPIO, 11', pin_signal: PTD11/LLWU_P25/SPI2_PCS0/SDHC0_CLKIN/LPUART0_CTS_b/FB_A19, direction: OUTPUT, gpio_init_state: 'true',
    pull_select: up}
  - {pin_num: '141', peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FB_A20, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '142', peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '143', peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '144', peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, direction: OUTPUT, gpio_init_state: 'true', pull_select: up}
  - {pin_num: '15', peripheral: GPIOE, signal: 'GPIO, 12', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, direction: OUTPUT, pull_select: down}
  - {pin_num: '96', peripheral: GPIOB, signal: 'GPIO, 17', pin_signal: TSI0_CH10/PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/SDRAM_D16/EWM_OUT_b/TPM_CLKIN1, direction: INPUT,
    pull_select: up}
  - {pin_num: '97', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: TSI0_CH11/PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/SDRAM_A23/FTM2_QD_PHA/TPM2_CH0, direction: INPUT,
    pull_select: up}
  - {pin_num: '112', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/USB0_SOF_OUT/I2S0_RX_FS/FB_AD8/SDRAM_A16, direction: INPUT, pull_select: up}
  - {pin_num: '123', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b/SDRAM_DQM2,
    direction: INPUT, pull_select: up}
  - {pin_num: '124', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: PTC17/CAN1_TX/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b/SDRAM_DQM3, direction: INPUT,
    pull_select: up}
  - {pin_num: '125', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b/SDRAM_DQM1, direction: INPUT,
    pull_select: up}
  - {pin_num: '99', peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/SPI2_PCS0/FB_AD31/SDRAM_D31/CMP0_OUT, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge,
    pull_select: up}
  - {pin_num: '98', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: TSI0_CH12/PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB/TPM2_CH1, direction: INPUT,
    pull_select: up}
  - {pin_num: '100', peripheral: GPIOB, signal: 'GPIO, 21', pin_signal: PTB21/SPI2_SCK/FB_AD30/SDRAM_D30/CMP1_OUT, direction: INPUT, pull_select: up}
  - {pin_num: '14', peripheral: I2C3, signal: SCL, pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6, open_drain: disable, pull_select: up}
  - {pin_num: '13', peripheral: I2C3, signal: SDA, pin_signal: PTE10/LLWU_P18/I2C3_SDA/I2S0_TXD0/LPUART0_CTS_b/FTM3_CH5/USB1_ID, open_drain: enable, pull_select: up}
  - {pin_num: '77', peripheral: GPIOA, signal: 'GPIO, 26', pin_signal: PTA26/MII0_TXD3/FB_A27, direction: OUTPUT}
  - {pin_num: '78', peripheral: GPIOA, signal: 'GPIO, 27', pin_signal: PTA27/MII0_CRS/FB_A26, direction: OUTPUT}
  - {pin_num: '79', peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTA28/MII0_TXER/FB_A25, direction: OUTPUT}
  - {pin_num: '80', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTA29/MII0_COL/FB_A24, direction: OUTPUT}
  - {pin_num: '81', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0,
    direction: INPUT}
  - {pin_num: '82', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1,
    direction: INPUT}
  - {pin_num: '83', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/UART0_RTS_b/ENET0_1588_TMR0/SDRAM_WE/FTM0_FLT3, identifier: CAMD2,
    direction: INPUT}
  - {pin_num: '84', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/SDRAM_CS0_b/FTM0_FLT0,
    direction: INPUT}
  - {pin_num: '85', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/SDRAM_CS1_b/FTM1_FLT0, direction: INPUT}
  - {pin_num: '86', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: ADC1_SE11/PTB5/ENET0_1588_TMR3/FTM2_FLT0, direction: INPUT}
  - {pin_num: '87', peripheral: GPIOB, signal: 'GPIO, 6', pin_signal: ADC1_SE12/PTB6/FB_AD23/SDRAM_D23, direction: INPUT}
  - {pin_num: '88', peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: ADC1_SE13/PTB7/FB_AD22/SDRAM_D22, direction: INPUT}
  - {pin_num: '89', peripheral: GPIOB, signal: 'GPIO, 8', pin_signal: PTB8/UART3_RTS_b/FB_AD21/SDRAM_D21, direction: INPUT, gpio_interrupt: kPORT_DMARisingEdge, slew_rate: fast,
    pull_select: down, pull_enable: disable}
  - {pin_num: '90', peripheral: GPIOB, signal: 'GPIO, 9', pin_signal: PTB9/SPI1_PCS1/UART3_CTS_b/FB_AD20/SDRAM_D20, direction: OUTPUT, gpio_init_state: 'true', pull_select: up,
    pull_enable: enable}
  - {pin_num: '91', peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/SDRAM_D19/FTM0_FLT1, direction: OUTPUT, gpio_init_state: 'true',
    open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '92', peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/SDRAM_D18/FTM0_FLT2, identifier: CAMHREF, direction: INPUT,
    gpio_interrupt: kPORT_InterruptFallingEdge, pull_select: down, pull_enable: disable}
  - {pin_num: '95', peripheral: GPIOB, signal: 'GPIO, 16', pin_signal: TSI0_CH9/PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/SDRAM_D17/EWM_IN/TPM_CLKIN0, direction: INPUT,
    gpio_interrupt: kPORT_InterruptFallingEdge, pull_select: up, pull_enable: disable}
  - {pin_num: '66', peripheral: UART0, signal: TX, pin_signal: PTA14/SPI0_PCS0/UART0_TX/RMII0_CRS_DV/MII0_RXDV/I2C2_SCL/I2S0_RX_BCLK/I2S0_TXD1, identifier: DbgUart_TX,
    direction: OUTPUT}
  - {pin_num: '67', peripheral: UART0, signal: RX, pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, identifier: DbgUart_RX}
  - {pin_num: '28', peripheral: ADC0, signal: 'SE, 19', pin_signal: ADC0_DM0/ADC1_DM3}
  - {pin_num: '29', peripheral: ADC0, signal: 'SE, 3', pin_signal: ADC1_DP0/ADC0_DP3}
  - {pin_num: '30', peripheral: ADC1, signal: 'SE, 19', pin_signal: ADC1_DM0/ADC0_DM3}
  - {pin_num: '110', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, direction: OUTPUT}
  - {pin_num: '111', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK, direction: OUTPUT}
  - {pin_num: '103', peripheral: ADC0, signal: 'SE, 14', pin_signal: ADC0_SE14/TSI0_CH13/PTC0/SPI0_PCS4/PDB0_EXTRG/USB0_SOF_OUT/FB_AD14/SDRAM_A22/I2S0_TXD1}
  - {pin_num: '127', peripheral: FTM3, signal: 'CH, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: OUTPUT}
  - {pin_num: '128', peripheral: FTM3, signal: 'CH, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: OUTPUT}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TPM1_CH1/TRACE_D1, direction: OUTPUT}
  - {pin_num: '120', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24, direction: OUTPUT}
  - {pin_num: '55', peripheral: FTM0, signal: 'CH, 2', pin_signal: PTA5/USB0_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, direction: OUTPUT}
  - {pin_num: '58', peripheral: FTM0, signal: 'CH, 3', pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, direction: OUTPUT}
  - {pin_num: '131', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, direction: OUTPUT}
  - {pin_num: '136', peripheral: FTM0, signal: 'CH, 7', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, direction: OUTPUT}
  - {pin_num: '133', peripheral: ADC0, signal: 'SE, 7b', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT}
  - {pin_num: '37', peripheral: ADC1, signal: 'SE, 18', pin_signal: VREF_OUT/CMP1_IN5/CMP0_IN5/ADC1_SE18}
  - {pin_num: '38', peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: '39', peripheral: ADC1, signal: 'SE, 23', pin_signal: DAC1_OUT/CMP0_IN4/CMP2_IN3/ADC1_SE23}
  - {pin_num: '45', peripheral: ADC0, signal: 'SE, 17', pin_signal: ADC0_SE17/PTE24/CAN1_TX/UART4_TX/I2C0_SCL/EWM_OUT_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t MLEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin 61)  */
    GPIO_PinInit(BOARD_INITPINS_MLEN_GPIO, BOARD_INITPINS_MLEN_PIN, &MLEN_config);

    gpio_pin_config_t OLED_SCL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA26 (pin 77)  */
    GPIO_PinInit(BOARD_INITPINS_OLED_SCL_GPIO, BOARD_INITPINS_OLED_SCL_PIN, &OLED_SCL_config);

    gpio_pin_config_t OLED_SDA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA27 (pin 78)  */
    GPIO_PinInit(BOARD_INITPINS_OLED_SDA_GPIO, BOARD_INITPINS_OLED_SDA_PIN, &OLED_SDA_config);

    gpio_pin_config_t OLED_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA28 (pin 79)  */
    GPIO_PinInit(BOARD_INITPINS_OLED_RST_GPIO, BOARD_INITPINS_OLED_RST_PIN, &OLED_RST_config);

    gpio_pin_config_t OLED_DC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA29 (pin 80)  */
    GPIO_PinInit(BOARD_INITPINS_OLED_DC_GPIO, BOARD_INITPINS_OLED_DC_PIN, &OLED_DC_config);

    gpio_pin_config_t CAMD0_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 81)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD0_GPIO, BOARD_INITPINS_CAMD0_PIN, &CAMD0_config);

    gpio_pin_config_t CAMD1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 82)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD1_GPIO, BOARD_INITPINS_CAMD1_PIN, &CAMD1_config);

    gpio_pin_config_t CAMD2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 83)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD2_GPIO, BOARD_INITPINS_CAMD2_PIN, &CAMD2_config);

    gpio_pin_config_t CAMD3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 84)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD3_GPIO, BOARD_INITPINS_CAMD3_PIN, &CAMD3_config);

    gpio_pin_config_t CAMD4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin 85)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD4_GPIO, BOARD_INITPINS_CAMD4_PIN, &CAMD4_config);

    gpio_pin_config_t CAMD5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 86)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD5_GPIO, BOARD_INITPINS_CAMD5_PIN, &CAMD5_config);

    gpio_pin_config_t CAMD6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB6 (pin 87)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD6_GPIO, BOARD_INITPINS_CAMD6_PIN, &CAMD6_config);

    gpio_pin_config_t CAMD7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB7 (pin 88)  */
    GPIO_PinInit(BOARD_INITPINS_CAMD7_GPIO, BOARD_INITPINS_CAMD7_PIN, &CAMD7_config);

    gpio_pin_config_t CAMPCLK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB8 (pin 89)  */
    GPIO_PinInit(BOARD_INITPINS_CAMPCLK_GPIO, BOARD_INITPINS_CAMPCLK_PIN, &CAMPCLK_config);

    gpio_pin_config_t CAMSCL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin 90)  */
    GPIO_PinInit(BOARD_INITPINS_CAMSCL_GPIO, BOARD_INITPINS_CAMSCL_PIN, &CAMSCL_config);

    gpio_pin_config_t CAMSDA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB10 (pin 91)  */
    GPIO_PinInit(BOARD_INITPINS_CAMSDA_GPIO, BOARD_INITPINS_CAMSDA_PIN, &CAMSDA_config);

    gpio_pin_config_t CAMHREF_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB11 (pin 92)  */
    GPIO_PinInit(BOARD_INITPINS_CAMHREF_GPIO, BOARD_INITPINS_CAMHREF_PIN, &CAMHREF_config);

    gpio_pin_config_t CAMVSYN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB16 (pin 95)  */
    GPIO_PinInit(BOARD_INITPINS_CAMVSYN_GPIO, BOARD_INITPINS_CAMVSYN_PIN, &CAMVSYN_config);

    gpio_pin_config_t KEY1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB17 (pin 96)  */
    GPIO_PinInit(BOARD_INITPINS_KEY1_GPIO, BOARD_INITPINS_KEY1_PIN, &KEY1_config);

    gpio_pin_config_t KEY2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 97)  */
    GPIO_PinInit(BOARD_INITPINS_KEY2_GPIO, BOARD_INITPINS_KEY2_PIN, &KEY2_config);

    gpio_pin_config_t QESb_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 98)  */
    GPIO_PinInit(BOARD_INITPINS_QESb_GPIO, BOARD_INITPINS_QESb_PIN, &QESb_config);

    gpio_pin_config_t QESa_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin 99)  */
    GPIO_PinInit(BOARD_INITPINS_QESa_GPIO, BOARD_INITPINS_QESa_PIN, &QESa_config);

    gpio_pin_config_t QESp_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB21 (pin 100)  */
    GPIO_PinInit(BOARD_INITPINS_QESp_GPIO, BOARD_INITPINS_QESp_PIN, &QESp_config);

    gpio_pin_config_t CCDCLK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 110)  */
    GPIO_PinInit(BOARD_INITPINS_CCDCLK_GPIO, BOARD_INITPINS_CCDCLK_PIN, &CCDCLK_config);

    gpio_pin_config_t CCDSI_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 111)  */
    GPIO_PinInit(BOARD_INITPINS_CCDSI_GPIO, BOARD_INITPINS_CCDSI_PIN, &CCDSI_config);

    gpio_pin_config_t SW1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC7 (pin 112)  */
    GPIO_PinInit(BOARD_INITPINS_SW1_GPIO, BOARD_INITPINS_SW1_PIN, &SW1_config);

    gpio_pin_config_t MREN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC15 (pin 120)  */
    GPIO_PinInit(BOARD_INITPINS_MREN_GPIO, BOARD_INITPINS_MREN_PIN, &MREN_config);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 123)  */
    GPIO_PinInit(BOARD_INITPINS_SW2_GPIO, BOARD_INITPINS_SW2_PIN, &SW2_config);

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC17 (pin 124)  */
    GPIO_PinInit(BOARD_INITPINS_SW3_GPIO, BOARD_INITPINS_SW3_PIN, &SW3_config);

    gpio_pin_config_t SW4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC18 (pin 125)  */
    GPIO_PinInit(BOARD_INITPINS_SW4_GPIO, BOARD_INITPINS_SW4_PIN, &SW4_config);

    gpio_pin_config_t DSPdp_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD8 (pin 137)  */
    GPIO_PinInit(BOARD_INITPINS_DSPdp_GPIO, BOARD_INITPINS_DSPdp_PIN, &DSPdp_config);

    gpio_pin_config_t DSPa_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD9 (pin 138)  */
    GPIO_PinInit(BOARD_INITPINS_DSPa_GPIO, BOARD_INITPINS_DSPa_PIN, &DSPa_config);

    gpio_pin_config_t DSPb_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD10 (pin 139)  */
    GPIO_PinInit(BOARD_INITPINS_DSPb_GPIO, BOARD_INITPINS_DSPb_PIN, &DSPb_config);

    gpio_pin_config_t DSPc_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD11 (pin 140)  */
    GPIO_PinInit(BOARD_INITPINS_DSPc_GPIO, BOARD_INITPINS_DSPc_PIN, &DSPc_config);

    gpio_pin_config_t DSPd_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD12 (pin 141)  */
    GPIO_PinInit(BOARD_INITPINS_DSPd_GPIO, BOARD_INITPINS_DSPd_PIN, &DSPd_config);

    gpio_pin_config_t DSPe_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD13 (pin 142)  */
    GPIO_PinInit(BOARD_INITPINS_DSPe_GPIO, BOARD_INITPINS_DSPe_PIN, &DSPe_config);

    gpio_pin_config_t DSPf_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD14 (pin 143)  */
    GPIO_PinInit(BOARD_INITPINS_DSPf_GPIO, BOARD_INITPINS_DSPf_PIN, &DSPf_config);

    gpio_pin_config_t DSPg_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin 144)  */
    GPIO_PinInit(BOARD_INITPINS_DSPg_GPIO, BOARD_INITPINS_DSPg_PIN, &DSPg_config);

    gpio_pin_config_t LED1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE8 (pin 11)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_GPIO, BOARD_INITPINS_LED1_PIN, &LED1_config);

    gpio_pin_config_t LED2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE9 (pin 12)  */
    GPIO_PinInit(BOARD_INITPINS_LED2_GPIO, BOARD_INITPINS_LED2_PIN, &LED2_config);

    gpio_pin_config_t BEEP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE12 (pin 15)  */
    GPIO_PinInit(BOARD_INITPINS_BEEP_GPIO, BOARD_INITPINS_BEEP_PIN, &BEEP_config);

    /* PORTA14 (pin 66) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DbgUart_TX_PORT, BOARD_INITPINS_DbgUart_TX_PIN, kPORT_MuxAlt3);

    /* PORTA15 (pin 67) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DbgUart_RX_PORT, BOARD_INITPINS_DbgUart_RX_PIN, kPORT_MuxAlt3);

    /* PORTA26 (pin 77) is configured as PTA26 */
    PORT_SetPinMux(BOARD_INITPINS_OLED_SCL_PORT, BOARD_INITPINS_OLED_SCL_PIN, kPORT_MuxAsGpio);

    /* PORTA27 (pin 78) is configured as PTA27 */
    PORT_SetPinMux(BOARD_INITPINS_OLED_SDA_PORT, BOARD_INITPINS_OLED_SDA_PIN, kPORT_MuxAsGpio);

    /* PORTA28 (pin 79) is configured as PTA28 */
    PORT_SetPinMux(BOARD_INITPINS_OLED_RST_PORT, BOARD_INITPINS_OLED_RST_PIN, kPORT_MuxAsGpio);

    /* PORTA29 (pin 80) is configured as PTA29 */
    PORT_SetPinMux(BOARD_INITPINS_OLED_DC_PORT, BOARD_INITPINS_OLED_DC_PIN, kPORT_MuxAsGpio);

    /* PORTA5 (pin 55) is configured as FTM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_ML0_PORT, BOARD_INITPINS_ML0_PIN, kPORT_MuxAlt3);

    /* PORTA6 (pin 58) is configured as FTM0_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_ML1_PORT, BOARD_INITPINS_ML1_PIN, kPORT_MuxAlt3);

    /* PORTA9 (pin 61) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_MLEN_PORT, BOARD_INITPINS_MLEN_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 81) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD0_PORT, BOARD_INITPINS_CAMD0_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 82) is configured as PTB1 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD1_PORT, BOARD_INITPINS_CAMD1_PIN, kPORT_MuxAsGpio);

    /* PORTB10 (pin 91) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_CAMSDA_PORT, BOARD_INITPINS_CAMSDA_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[10] = ((PORTB->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTB11 (pin 92) is configured as PTB11 */
    PORT_SetPinMux(BOARD_INITPINS_CAMHREF_PORT, BOARD_INITPINS_CAMHREF_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTB11 (pin 92): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_CAMHREF_PORT, BOARD_INITPINS_CAMHREF_PIN, kPORT_InterruptFallingEdge);

    PORTB->PCR[11] = ((PORTB->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullDown)

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTB16 (pin 95) is configured as PTB16 */
    PORT_SetPinMux(BOARD_INITPINS_CAMVSYN_PORT, BOARD_INITPINS_CAMVSYN_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTB16 (pin 95): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_CAMVSYN_PORT, BOARD_INITPINS_CAMVSYN_PIN, kPORT_InterruptFallingEdge);

    PORTB->PCR[16] = ((PORTB->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp)

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable));

    /* PORTB17 (pin 96) is configured as PTB17 */
    PORT_SetPinMux(BOARD_INITPINS_KEY1_PORT, BOARD_INITPINS_KEY1_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[17] = ((PORTB->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB18 (pin 97) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_KEY2_PORT, BOARD_INITPINS_KEY2_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[18] = ((PORTB->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB19 (pin 98) is configured as PTB19 */
    PORT_SetPinMux(BOARD_INITPINS_QESb_PORT, BOARD_INITPINS_QESb_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[19] = ((PORTB->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB2 (pin 83) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD2_PORT, BOARD_INITPINS_CAMD2_PIN, kPORT_MuxAsGpio);

    /* PORTB20 (pin 99) is configured as PTB20 */
    PORT_SetPinMux(BOARD_INITPINS_QESa_PORT, BOARD_INITPINS_QESa_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTB20 (pin 99): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_QESa_PORT, BOARD_INITPINS_QESa_PIN, kPORT_InterruptRisingEdge);

    PORTB->PCR[20] = ((PORTB->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB21 (pin 100) is configured as PTB21 */
    PORT_SetPinMux(BOARD_INITPINS_QESp_PORT, BOARD_INITPINS_QESp_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[21] = ((PORTB->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB3 (pin 84) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD3_PORT, BOARD_INITPINS_CAMD3_PIN, kPORT_MuxAsGpio);

    /* PORTB4 (pin 85) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD4_PORT, BOARD_INITPINS_CAMD4_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin 86) is configured as PTB5 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD5_PORT, BOARD_INITPINS_CAMD5_PIN, kPORT_MuxAsGpio);

    /* PORTB6 (pin 87) is configured as PTB6 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD6_PORT, BOARD_INITPINS_CAMD6_PIN, kPORT_MuxAsGpio);

    /* PORTB7 (pin 88) is configured as PTB7 */
    PORT_SetPinMux(BOARD_INITPINS_CAMD7_PORT, BOARD_INITPINS_CAMD7_PIN, kPORT_MuxAsGpio);

    /* PORTB8 (pin 89) is configured as PTB8 */
    PORT_SetPinMux(BOARD_INITPINS_CAMPCLK_PORT, BOARD_INITPINS_CAMPCLK_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTB8 (pin 89): DMA request on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_CAMPCLK_PORT, BOARD_INITPINS_CAMPCLK_PIN, kPORT_DMARisingEdge);

    PORTB->PCR[8] = ((PORTB->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable)

                     /* Slew Rate Enable: Fast slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_FastSlewRate));

    /* PORTB9 (pin 90) is configured as PTB9 */
    PORT_SetPinMux(BOARD_INITPINS_CAMSCL_PORT, BOARD_INITPINS_CAMSCL_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[9] = ((PORTB->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC0 (pin 103) is configured as ADC0_SE14 */
    PORT_SetPinMux(BOARD_INITPINS_CCDAO_PORT, BOARD_INITPINS_CCDAO_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTC15 (pin 120) is configured as PTC15 */
    PORT_SetPinMux(BOARD_INITPINS_MREN_PORT, BOARD_INITPINS_MREN_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 123) is configured as PTC16 */
    PORT_SetPinMux(BOARD_INITPINS_SW2_PORT, BOARD_INITPINS_SW2_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[16] = ((PORTC->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTC17 (pin 124) is configured as PTC17 */
    PORT_SetPinMux(BOARD_INITPINS_SW3_PORT, BOARD_INITPINS_SW3_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[17] = ((PORTC->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTC18 (pin 125) is configured as PTC18 */
    PORT_SetPinMux(BOARD_INITPINS_SW4_PORT, BOARD_INITPINS_SW4_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[18] = ((PORTC->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTC5 (pin 110) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_CCDCLK_PORT, BOARD_INITPINS_CCDCLK_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 111) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_CCDSI_PORT, BOARD_INITPINS_CCDSI_PIN, kPORT_MuxAsGpio);

    /* PORTC7 (pin 112) is configured as PTC7 */
    PORT_SetPinMux(BOARD_INITPINS_SW1_PORT, BOARD_INITPINS_SW1_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[7] = ((PORTC->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD0 (pin 127) is configured as FTM3_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_SERVO1_PORT, BOARD_INITPINS_SERVO1_PIN, kPORT_MuxAlt4);

    /* PORTD1 (pin 128) is configured as FTM3_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_SERVO2_PORT, BOARD_INITPINS_SERVO2_PIN, kPORT_MuxAlt4);

    /* PORTD10 (pin 139) is configured as PTD10 */
    PORT_SetPinMux(BOARD_INITPINS_DSPb_PORT, BOARD_INITPINS_DSPb_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[10] = ((PORTD->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD11 (pin 140) is configured as PTD11 */
    PORT_SetPinMux(BOARD_INITPINS_DSPc_PORT, BOARD_INITPINS_DSPc_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[11] = ((PORTD->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD12 (pin 141) is configured as PTD12 */
    PORT_SetPinMux(BOARD_INITPINS_DSPd_PORT, BOARD_INITPINS_DSPd_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[12] = ((PORTD->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD13 (pin 142) is configured as PTD13 */
    PORT_SetPinMux(BOARD_INITPINS_DSPe_PORT, BOARD_INITPINS_DSPe_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[13] = ((PORTD->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD14 (pin 143) is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_DSPf_PORT, BOARD_INITPINS_DSPf_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[14] = ((PORTD->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD15 (pin 144) is configured as PTD15 */
    PORT_SetPinMux(BOARD_INITPINS_DSPg_PORT, BOARD_INITPINS_DSPg_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[15] = ((PORTD->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD4 (pin 131) is configured as FTM0_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_MR0_PORT, BOARD_INITPINS_MR0_PIN, kPORT_MuxAlt4);

    /* PORTD6 (pin 133) is configured as ADC0_SE7b */
    PORT_SetPinMux(BOARD_INITPINS_VSENSE_PORT, BOARD_INITPINS_VSENSE_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTD7 (pin 136) is configured as FTM0_CH7 */
    PORT_SetPinMux(BOARD_INITPINS_MR1_PORT, BOARD_INITPINS_MR1_PIN, kPORT_MuxAlt4);

    /* PORTD8 (pin 137) is configured as PTD8 */
    PORT_SetPinMux(BOARD_INITPINS_DSPdp_PORT, BOARD_INITPINS_DSPdp_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[8] = ((PORTD->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTD9 (pin 138) is configured as PTD9 */
    PORT_SetPinMux(BOARD_INITPINS_DSPa_PORT, BOARD_INITPINS_DSPa_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[9] = ((PORTD->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTE10 (pin 13) is configured as I2C3_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C3_SDA_PORT, BOARD_INITPINS_I2C3_SDA_PIN, kPORT_MuxAlt2);

    PORTE->PCR[10] = ((PORTE->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable)

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTE11 (pin 14) is configured as I2C3_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C3_SCL_PORT, BOARD_INITPINS_I2C3_SCL_PIN, kPORT_MuxAlt2);

    PORTE->PCR[11] = ((PORTE->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Open Drain Enable: Open drain output is disabled on the corresponding pin. */
                      | PORT_PCR_ODE(kPORT_OpenDrainDisable)

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTE12 (pin 15) is configured as PTE12 */
    PORT_SetPinMux(BOARD_INITPINS_BEEP_PORT, BOARD_INITPINS_BEEP_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[12] = ((PORTE->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullDown));

    /* PORTE24 (pin 45) is configured as ADC0_SE17 */
    PORT_SetPinMux(BOARD_INITPINS_HALL2_PORT, BOARD_INITPINS_HALL2_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE8 (pin 11) is configured as PTE8 */
    PORT_SetPinMux(BOARD_INITPINS_LED1_PORT, BOARD_INITPINS_LED1_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[8] = ((PORTE->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTE9 (pin 12) is configured as PTE9 */
    PORT_SetPinMux(BOARD_INITPINS_LED2_PORT, BOARD_INITPINS_LED2_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[9] = ((PORTE->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
